# Generated by Django 5.1.7 on 2025-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='image_url',
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complexes/', verbose_name='Изображение'),
        ),
    ]
