# Generated by Django 5.1.7 on 2025-08-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_residentialcomplex_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcomplex',
            name='area_from',
            field=models.DecimalField(decimal_places=1, default=60.0, max_digits=6, verbose_name='Площадь от (м²)'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='area_to',
            field=models.DecimalField(decimal_places=1, default=120.0, max_digits=6, verbose_name='Площадь до (м²)'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сдачи'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='house_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('townhouse', 'Таунхаус'), ('penthouse', 'Пентхаус')], default='apartment', max_length=20, verbose_name='Тип дома'),
        ),
    ]
