# Generated by Django 5.1.7 on 2025-08-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_residentialcomplex_area_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcomplex',
            name='finishing',
            field=models.CharField(choices=[('finished', 'С отделкой'), ('unfinished', 'Без отделки')], default='unfinished', max_length=20, verbose_name='Отделка'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='house_class',
            field=models.CharField(choices=[('economy', 'Эконом-класс'), ('comfort', 'Комфорт-класс'), ('premium', 'Премиум-класс')], default='comfort', max_length=20, verbose_name='Класс жилья'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='status',
            field=models.CharField(choices=[('completed', 'Сдан'), ('construction', 'Строится')], default='construction', max_length=20, verbose_name='Статус'),
        ),
    ]
