# Generated by Django 5.1.7 on 2025-08-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_residentialcomplex_finishing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='location',
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='city',
            field=models.CharField(default='Уфа', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='rooms',
            field=models.CharField(choices=[('1', '1 комната'), ('2', '2 комнаты'), ('3', '3 комнаты'), ('4', '4+ комнаты')], default='2', max_length=10, verbose_name='Количество комнат'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Улица'),
        ),
    ]
