# Generated by Django 5.1.7 on 2025-08-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_residentialcomplex_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcomplex',
            name='completion_end',
            field=models.CharField(default='4 кв. 2025', max_length=20, verbose_name='Окончание сдачи'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='completion_start',
            field=models.CharField(default='3 кв. 2024', max_length=20, verbose_name='Начало сдачи'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='developer',
            field=models.CharField(default='Антон Хаус', max_length=100, verbose_name='Застройщик'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='four_room_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена 4+ комнатной (млн)'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='has_completed',
            field=models.BooleanField(default=False, verbose_name='Есть сданные'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='complexes/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='complexes/', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='complexes/', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='metro_station',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ближайшее метро'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='metro_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='Время до метро'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='mortgage_monthly',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ипотека в месяц'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='one_room_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена 1-комнатной (млн)'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='studio_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена студии (млн)'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='three_room_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена 3-комнатной (млн)'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='total_apartments',
            field=models.IntegerField(default=100, verbose_name='Общее количество квартир'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='two_room_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена 2-комнатной (млн)'),
        ),
    ]
