# Generated by Django 5.1.7 on 2025-08-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_residentialcomplex_completion_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='metro_station',
        ),
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='metro_time',
        ),
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='mortgage_monthly',
        ),
    ]
