# Generated by Django 5.2.4 on 2025-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_residentialcomplex_metro_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('category', models.CharField(choices=[('mortgage', 'Ипотека'), ('laws', 'Законы'), ('instructions', 'Инструкции'), ('market', 'Рынок недвижимости'), ('tips', 'Советы')], default='tips', max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Изображение')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_date'],
            },
        ),
    ]
