# Generated by Django 5.2.4 on 2025-08-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tag_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Фото автора')),
                ('description', models.TextField(blank=True, verbose_name='Описание автора')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('articles_count', models.IntegerField(default=0, verbose_name='Количество статей')),
                ('total_views', models.IntegerField(default=0, verbose_name='Общее количество просмотров')),
                ('total_likes', models.IntegerField(default=0, verbose_name='Общее количество лайков')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='comments_count',
            field=models.IntegerField(default=0, verbose_name='Количество комментариев'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, to='main.article', verbose_name='Похожие статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.author', verbose_name='Автор'),
        ),
    ]
