# Generated by Django 5.2.4 on 2025-08-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_author_article_comments_count_article_likes_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=100, verbose_name='Имя основателя')),
                ('founder_photo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Фото основателя')),
                ('founder_position', models.CharField(default='основатель компании', max_length=200, verbose_name='Должность основателя')),
                ('company_name', models.CharField(default='Антон Хаус', max_length=100, verbose_name='Название компании')),
                ('quote', models.TextField(verbose_name='Цитата основателя')),
                ('description', models.TextField(blank=True, verbose_name='Описание компании')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
    ]
