# Generated by Django 5.2.4 on 2025-08-04 15:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Краткое описание'),
        ),
    ]
