# Generated by Django 5.2.4 on 2025-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_article_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('kind', models.CharField(choices=[('newbuild', 'Новостройки'), ('secondary', 'Вторичная недвижимость')], max_length=20, verbose_name='Тип страницы')),
                ('category', models.CharField(choices=[('apartment', 'Квартиры'), ('house', 'Дома'), ('cottage', 'Коттеджи'), ('townhouse', 'Таунхаусы'), ('commercial', 'Коммерческие помещения'), ('all', 'Все объекты')], default='all', max_length=20, verbose_name='Категория')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
            ],
            options={
                'verbose_name': 'Страница каталога',
                'verbose_name_plural': 'Страницы каталога',
                'ordering': ['name'],
            },
        ),
    ]
