# Generated by Django 5.2.4 on 2025-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cataloglanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена (млн)')),
                ('city', models.CharField(default='Уфа', max_length=100, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Улица')),
                ('commute_time', models.CharField(default='10 минут', max_length=50, verbose_name='Время в пути')),
                ('image', models.ImageField(blank=True, null=True, upload_to='secondary/', verbose_name='Изображение')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='secondary/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='secondary/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='secondary/', verbose_name='Изображение 4')),
                ('house_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Частный дом'), ('cottage', 'Коттедж'), ('townhouse', 'Таунхаус'), ('commercial', 'Коммерческое помещение')], default='apartment', max_length=20, verbose_name='Тип объекта')),
                ('area', models.DecimalField(decimal_places=1, default=45.0, max_digits=7, verbose_name='Площадь (м²)')),
                ('rooms', models.CharField(choices=[('1', '1 комната'), ('2', '2 комнаты'), ('3', '3 комнаты'), ('4', '4+ комнаты')], default='2', max_length=10, verbose_name='Комнат')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вторичная недвижимость',
                'verbose_name_plural': 'Вторичная недвижимость',
                'ordering': ['-created_at'],
            },
        ),
    ]
