# Generated by Django 5.2.4 on 2025-08-11 09:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_secondaryproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=tinymce.models.HTMLField(max_length=500, verbose_name='Краткое описание'),
        ),
    ]
