# Generated by Django 5.2.4 on 2025-08-12 04:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_residentialcomplex_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Отдел')),
                ('city', models.CharField(default='Уфа', max_length=100, verbose_name='Город')),
                ('employment_type', models.CharField(choices=[('fulltime', 'Полная занятость'), ('parttime', 'Частичная занятость'), ('contract', 'Контракт'), ('intern', 'Стажировка'), ('remote', 'Удаленная работа')], default='fulltime', max_length=20, verbose_name='Тип занятости')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата до')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('responsibilities', tinymce.models.HTMLField(blank=True, verbose_name='Обязанности')),
                ('requirements', tinymce.models.HTMLField(blank=True, verbose_name='Требования')),
                ('benefits', tinymce.models.HTMLField(blank=True, verbose_name='Условия')),
                ('contact_email', models.EmailField(default='hr@antonhaus.ru', max_length=254, verbose_name='Email для отклика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_date'],
            },
        ),
    ]
