# Generated by Django 5.2.4 on 2025-08-12 05:38

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_branchoffice_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок видео')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Описание')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео (YouTube и т.п.)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Файл видео')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Превью')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('related_videos', models.ManyToManyField(blank=True, to='main.residentialvideo', verbose_name='Похожие видео')),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.residentialcomplex', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Видеообзор ЖК',
                'verbose_name_plural': 'Видеообзоры ЖК',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрено')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.residentialvideo', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Комментарий к видео',
                'verbose_name_plural': 'Комментарии к видео',
                'ordering': ['-created_at'],
            },
        ),
    ]
