# Generated by Django 5.2.4 on 2025-08-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_mortgageprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageprogram',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
