# Generated by Django 5.2.4 on 2025-08-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_mortgageprogram_id'),
        ('main', '0024_specialoffer'),
    ]

    operations = [
    ]
