# Generated by Django 5.2.4 on 2025-08-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_merge_0024_alter_mortgageprogram_id_0024_specialoffer'),
        ('main', '0025_specialoffer_image'),
    ]

    operations = [
    ]
