# Generated by Django 5.2.4 on 2025-08-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_merge_20250813_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
