# Generated by Django 5.2.4 on 2025-08-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_article_article_type'),
        ('main', '0028_specialoffer_expires_at'),
    ]

    operations = [
    ]
