# Generated by Django 5.2.4 on 2025-08-21 19:22

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-is_featured', 'full_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='employee',
            name='achievements',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание агента'),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый агент'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specializations',
            field=models.TextField(blank=True, verbose_name='Специализации'),
        ),
        migrations.AddField(
            model_name='employee',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='company/videos/', verbose_name='Файл видео'),
        ),
        migrations.AddField(
            model_name='employee',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (YouTube)'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residential_complexes', to='main.employee', verbose_name='Ответственный агент'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_properties', to='main.employee', verbose_name='Ответственный агент'),
        ),
        migrations.CreateModel(
            name='EmployeeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя клиента')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email клиента')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон клиента')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отзыв о сотруднике',
                'verbose_name_plural': 'Отзывы о сотрудниках',
                'ordering': ['-created_at'],
            },
        ),
    ]
