# Generated by Django 5.2.4 on 2025-08-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_companygallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('residential_complex', 'Жилые комплексы'), ('employee', 'Сотрудники'), ('company', 'Компания'), ('article', 'Статьи'), ('special_offer', 'Акции'), ('office', 'Офисы'), ('video', 'Видео')], max_length=50, verbose_name='Категория')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
                'ordering': ['category', 'object_id', 'order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CompanyGallery',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='branchoffice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='branchoffice',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='founder_photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='image',
        ),
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='residentialvideo',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='secondaryproperty',
            name='image',
        ),
        migrations.RemoveField(
            model_name='secondaryproperty',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='secondaryproperty',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='secondaryproperty',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='specialoffer',
            name='image',
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['category', 'object_id'], name='main_galler_categor_ae991a_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['is_active', 'is_main'], name='main_galler_is_acti_7135c4_idx'),
        ),
    ]
