# Generated by Django 5.2.4 on 2025-08-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_gallery_delete_companygallery_remove_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('residential_complex', 'Жилые комплексы'), ('secondary_property', 'Вторичная недвижимость'), ('employee', 'Сотрудники'), ('company', 'Компания'), ('article', 'Статьи'), ('special_offer', 'Акции'), ('office', 'Офисы'), ('video', 'Видео')], max_length=50, verbose_name='Категория'),
        ),
    ]
