# Generated by Django 5.2.4 on 2025-08-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_gallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='content_type',
            field=models.CharField(choices=[('image', 'Фото'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип контента'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/', verbose_name='Файл видео'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (YouTube)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('residential_complex', 'Жилые комплексы'), ('secondary_property', 'Вторичная недвижимость'), ('employee', 'Сотрудники'), ('company', 'Компания'), ('article', 'Статьи'), ('special_offer', 'Акции'), ('office', 'Офисы'), ('employee_video', 'Видео сотрудников'), ('residential_video', 'Видео жилых комплексов')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное фото/видео'),
        ),
    ]
