# Generated by Django 5.2.4 on 2025-08-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_gallery_content_type_gallery_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocomment',
            name='video',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('residential_complex', 'Жилые комплексы'), ('secondary_property', 'Вторичная недвижимость'), ('employee', 'Сотрудники'), ('company', 'Компания'), ('article', 'Статьи'), ('special_offer', 'Акции'), ('office', 'Офисы'), ('employee_video', 'Видео сотрудников'), ('residential_video', 'Видео жилых комплексов'), ('secondary_video', 'Видео вторичной недвижимости')], max_length=50, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='ResidentialVideo',
        ),
        migrations.DeleteModel(
            name='VideoComment',
        ),
    ]
