# Generated by Django 5.2.4 on 2025-08-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_videocomment_video_alter_gallery_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/', verbose_name='Превью видео'),
        ),
    ]
