# Generated by Django 5.2.4 on 2025-08-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_gallery_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ЖК')),
                ('description', models.TextField(verbose_name='Описание')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Улица')),
                ('delivery_date', models.DateField(verbose_name='Срок сдачи')),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена от (млн ₽)')),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена до (млн ₽)')),
                ('area_from', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Площадь от (м²)')),
                ('area_to', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Площадь до (м²)')),
                ('rooms', models.CharField(blank=True, max_length=50, verbose_name='Количество комнат')),
                ('house_class', models.CharField(blank=True, max_length=50, verbose_name='Класс дома')),
                ('developer', models.CharField(blank=True, max_length=200, verbose_name='Застройщик')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Будущий ЖК',
                'verbose_name_plural': 'Будущие ЖК',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('residential_complex', 'Жилые комплексы'), ('secondary_property', 'Вторичная недвижимость'), ('employee', 'Сотрудники'), ('company', 'Компания'), ('article', 'Статьи'), ('special_offer', 'Акции'), ('office', 'Офисы'), ('employee_video', 'Видео сотрудников'), ('residential_video', 'Видео жилых комплексов'), ('secondary_video', 'Видео вторичной недвижимости'), ('future_complex', 'Будущие ЖК')], max_length=50, verbose_name='Категория'),
        ),
    ]
