# Generated by Django 5.2.4 on 2025-09-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_futurecomplex_alter_gallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='is_head_office',
            field=models.BooleanField(default=False, verbose_name='Головной офис'),
        ),
    ]
