# Generated by Django 5.2.4 on 2025-09-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_branchoffice_is_head_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcomplex',
            name='highlight_recommended',
            field=models.BooleanField(default=False, verbose_name='Подсветить как рекомендуюмую'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='highlight_sale',
            field=models.BooleanField(default=False, verbose_name='Подсветить как акцию'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='highlight_recommended',
            field=models.BooleanField(default=False, verbose_name='Подсветить как рекомендуюмую'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='highlight_sale',
            field=models.BooleanField(default=False, verbose_name='Подсветить как акцию'),
        ),
    ]
