# Generated by Django 5.2.4 on 2025-09-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_residentialcomplex_highlight_recommended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='video_thumbnail',
        ),
    ]
