# Generated by Django 5.2.4 on 2025-10-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_gallery_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='highlight_recommended',
        ),
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='highlight_sale',
        ),
        migrations.RemoveField(
            model_name='secondaryproperty',
            name='highlight_recommended',
        ),
        migrations.RemoveField(
            model_name='secondaryproperty',
            name='highlight_sale',
        ),
    ]
