from django.core.management.base import BaseCommand
from main.models import ResidentialComplex

class Command(BaseCommand):
    help = 'Создает тестовые данные для жилых комплексов'

    def handle(self, *args, **options):
        # Очищаем существующие данные
        ResidentialComplex.objects.all().delete()
        
        # Создаем 20 тестовых ЖК с полными параметрами
        complexes_data = [
            {
                'name': 'Горки Парк',
                'price_from': 4.0,
                'city': 'Уфа',
                'district': 'Калининский',
                'street': 'Домодедовская',
                'commute_time': '18 мин.',
                'house_type': 'apartment',
                'area_from': 60.0,
                'area_to': 120.0,
                'status': 'completed',
                'house_class': 'comfort',
                'finishing': 'finished',
                'rooms': '2',
                'total_apartments': 271,
                'completion_start': '3 кв. 2024',
                'completion_end': '4 кв. 2025',
                'has_completed': True,
                'developer': 'Антон Хаус',
                'studio_price': 4.1,
                'one_room_price': 4.5,
                'two_room_price': 4.0,
                'three_room_price': 5.2,
                'four_room_price': 7.8,
                'is_featured': True
            },
            {
                'name': 'Пригород Лесное',
                'price_from': 3.6,
                'city': 'Уфа',
                'district': 'Орджоникидзевский',
                'street': 'Лесная',
                'commute_time': '15 мин.',
                'house_type': 'house',
                'area_from': 80.0,
                'area_to': 150.0,
                'status': 'construction',
                'house_class': 'comfort',
                'finishing': 'unfinished',
                'rooms': '3',
                'total_apartments': 156,
                'completion_start': '2 кв. 2024',
                'completion_end': '3 кв. 2025',
                'has_completed': False,
                'developer': 'Антон Хаус',
                'studio_price': 3.6,
                'one_room_price': 4.2,
                'two_room_price': 5.1,
                'three_room_price': 6.8,
                'four_room_price': 9.2,
                'is_featured': True
            },
            {
                'name': 'Богдановский Лес',
                'price_from': 3.6,
                'city': 'Уфа',
                'district': 'Советский',
                'street': 'Богдановская',
                'commute_time': '30 мин.',
                'house_type': 'townhouse',
                'area_from': 100.0,
                'area_to': 180.0,
                'status': 'construction',
                'house_class': 'premium',
                'finishing': 'unfinished',
                'rooms': '4',
                'total_apartments': 89,
                'completion_start': '1 кв. 2024',
                'completion_end': '2 кв. 2025',
                'has_completed': False,
                'developer': 'Антон Хаус',
                'studio_price': 3.6,
                'one_room_price': 4.8,
                'two_room_price': 6.2,
                'three_room_price': 8.5,
                'four_room_price': 12.1,
                'is_featured': True
            },
            {
                'name': 'Солнечный Град',
                'price_from': 4.2,
                'city': 'Уфа',
                'district': 'Ленинский',
                'street': 'Центральная',
                'commute_time': '10 мин.',
                'house_type': 'apartment',
                'area_from': 45.0,
                'area_to': 90.0,
                'status': 'completed',
                'house_class': 'economy',
                'finishing': 'finished',
                'rooms': '1',
                'total_apartments': 342,
                'completion_start': '4 кв. 2023',
                'completion_end': '1 кв. 2025',
                'has_completed': True,
                'developer': 'Антон Хаус',
                'studio_price': 4.2,
                'one_room_price': 4.2,
                'two_room_price': 5.1,
                'three_room_price': 6.8,
                'four_room_price': 8.9,
                'is_featured': True
            },
            {
                'name': 'Зеленый Оазис',
                'price_from': 3.8,
                'city': 'Уфа',
                'district': 'Демский',
                'street': 'Загородная',
                'commute_time': '25 мин.',
                'house_type': 'house',
                'area_from': 120.0,
                'area_to': 200.0,
                'status': 'construction',
                'house_class': 'premium',
                'finishing': 'unfinished',
                'rooms': '4',
                'total_apartments': 67,
                'completion_start': '2 кв. 2024',
                'completion_end': '4 кв. 2025',
                'has_completed': False,
                'developer': 'Антон Хаус',
                'studio_price': 3.8,
                'one_room_price': 4.5,
                'two_room_price': 6.1,
                'three_room_price': 8.2,
                'four_room_price': 11.8,
                'is_featured': True
            },
            {
                'name': 'Речной Берег',
                'price_from': 5.1,
                'city': 'Уфа',
                'district': 'Кировский',
                'street': 'Набережная',
                'commute_time': '12 мин.',
                'house_type': 'penthouse',
                'area_from': 150.0,
                'area_to': 300.0,
                'status': 'completed',
                'house_class': 'premium',
                'finishing': 'finished',
                'rooms': '4',
                'total_apartments': 45,
                'completion_start': '3 кв. 2023',
                'completion_end': '1 кв. 2025',
                'has_completed': True,
                'developer': 'Антон Хаус',
                'studio_price': 5.1,
                'one_room_price': 6.2,
                'two_room_price': 8.5,
                'three_room_price': 12.1,
                'four_room_price': 18.9,
                'is_featured': True
            },
            {
                'name': 'Университетский',
                'price_from': 3.2,
                'city': 'Уфа',
                'district': 'Октябрьский',
                'street': 'Академическая',
                'commute_time': '8 мин.',
                'house_type': 'apartment',
                'area_from': 35.0,
                'area_to': 75.0,
                'status': 'completed',
                'house_class': 'economy',
                'finishing': 'finished',
                'rooms': '1',
                'total_apartments': 298,
                'completion_start': '1 кв. 2024',
                'completion_end': '3 кв. 2025',
                'has_completed': True,
                'developer': 'Антон Хаус',
                'studio_price': 3.2,
                'one_room_price': 3.2,
                'two_room_price': 4.1,
                'three_room_price': 5.2,
                'four_room_price': 6.8,
                'is_featured': True
            },
            {
                'name': 'Бизнес Квартал',
                'price_from': 6.5,
                'city': 'Уфа',
                'district': 'Ленинский',
                'street': 'Деловой центр',
                'commute_time': '5 мин.',
                'house_type': 'penthouse',
                'area_from': 200.0,
                'area_to': 400.0,
                'status': 'completed',
                'house_class': 'premium',
                'finishing': 'finished',
                'rooms': '4',
                'total_apartments': 23,
                'completion_start': '2 кв. 2023',
                'completion_end': '4 кв. 2024',
                'has_completed': True,
                'developer': 'Антон Хаус',
                'studio_price': 6.5,
                'one_room_price': 7.8,
                'two_room_price': 10.2,
                'three_room_price': 14.5,
                'four_room_price': 22.1,
                'is_featured': True
            },
            {
                'name': 'Парк Победы',
                'price_from': 4.8,
                'city': 'Уфа',
                'district': 'Калининский',
                'street': 'Парк Победы',
                'commute_time': '22 мин.',
                'house_type': 'apartment',
                'area_from': 55.0,
                'area_to': 110.0,
                'status': 'construction',
                'house_class': 'comfort',
                'finishing': 'unfinished',
                'rooms': '2',
                'total_apartments': 187,
                'completion_start': '3 кв. 2024',
                'completion_end': '2 кв. 2025',
                'has_completed': False,
                'developer': 'Антон Хаус',
                'studio_price': 4.8,
                'one_room_price': 5.2,
                'two_room_price': 4.8,
                'three_room_price': 6.8,
                'four_room_price': 9.1,
                'is_featured': True
            },
            {
                'name': 'Спортивная',
                'price_from': 3.9,
                'city': 'Уфа',
                'district': 'Орджоникидзевский',
                'street': 'Спортивная',
                'commute_time': '14 мин.',
                'house_type': 'apartment',
                'area_from': 50.0,
                'area_to': 95.0,
                'status': 'completed',
                'house_class': 'economy',
                'finishing': 'finished',
                'rooms': '2',
                'total_apartments': 234,
                'completion_start': '4 кв. 2023',
                'completion_end': '1 кв. 2025',
                'has_completed': True,
                'developer': 'Антон Хаус',
                'studio_price': 3.9,
                'one_room_price': 4.1,
                'two_room_price': 3.9,
                'three_room_price': 5.2,
                'four_room_price': 6.8,
                'is_featured': False
            },
            {
                'name': 'Молодежная',
                'price_from': 3.4,
                'city': 'Уфа',
                'district': 'Советский',
                'street': 'Молодежная',
                'commute_time': '16 мин.',
                'house_type': 'apartment',
                'area_from': 40.0,
                'area_to': 80.0,
                'status': 'construction',
                'house_class': 'economy',
                'finishing': 'unfinished',
                'rooms': '1',
                'total_apartments': 312,
                'completion_start': '1 кв. 2024',
                'completion_end': '3 кв. 2025',
                'has_completed': False,
                'developer': 'Антон Хаус',
                'studio_price': 3.4,
                'one_room_price': 3.4,
                'two_room_price': 4.2,
                'three_room_price': 5.1,
                'four_room_price': 6.8,
                'is_featured': False
            },
            {
                'name': 'Центральная',
                'price_from': 5.8,
                'city': 'Уфа',
                'district': 'Ленинский',
                'street': 'Центральная',
                'commute_time': '7 мин.',
                'house_type': 'apartment',
                'area_from': 70.0,
                'area_to': 140.0,
                'status': 'completed',
                'house_class': 'premium',
                'finishing': 'finished',
                'rooms': '3',
                'total_apartments': 156,
                'completion_start': '2 кв. 2023',
                'completion_end': '4 кв. 2024',
                'has_completed': True,
                'developer': 'Антон Хаус',
                'studio_price': 5.8,
                'one_room_price': 6.2,
                'two_room_price': 7.8,
                'three_room_price': 5.8,
                'four_room_price': 9.8,
                'is_featured': False
            },
            {
                'name': 'Лесная Поляна',
                'price_from': 3.1,
                'city': 'Уфа',
                'district': 'Демский',
                'street': 'Лесная',
                'commute_time': '28 мин.',
                'house_type': 'house',
                'area_from': 90.0,
                'area_to': 160.0,
                'status': 'construction',
                'house_class': 'comfort',
                'finishing': 'unfinished',
                'rooms': '3',
                'total_apartments': 78,
                'completion_start': '3 кв. 2024',
                'completion_end': '1 кв. 2026',
                'has_completed': False,
                'developer': 'Антон Хаус',
                'studio_price': 3.1,
                'one_room_price': 3.8,
                'two_room_price': 4.9,
                'three_room_price': 3.1,
                'four_room_price': 7.2,
                'is_featured': False
            },
            {
                'name': 'Речной Порт',
                'price_from': 4.5,
                'city': 'Уфа',
                'district': 'Кировский',
                'street': 'Речной порт',
                'commute_time': '20 мин.',
                'house_type': 'apartment',
                'area_from': 65.0,
                'area_to': 130.0,
                'status': 'completed',
                'house_class': 'comfort',
                'finishing': 'finished',
                'rooms': '2',
                'total_apartments': 198,
                'completion_start': '1 кв. 2024',
                'completion_end': '2 кв. 2025',
                'has_completed': True,
                'developer': 'Антон Хаус',
                'studio_price': 4.5,
                'one_room_price': 4.8,
                'two_room_price': 4.5,
                'three_room_price': 6.2,
                'four_room_price': 8.1,
                'is_featured': False
            },
            {
                'name': 'Аэропорт',
                'price_from': 2.8,
                'city': 'Уфа',
                'district': 'Октябрьский',
                'street': 'Аэропорт',
                'commute_time': '35 мин.',
                'house_type': 'apartment',
                'area_from': 45.0,
                'area_to': 85.0,
                'status': 'construction',
                'house_class': 'economy',
                'finishing': 'unfinished',
                'rooms': '1',
                'total_apartments': 445,
                'completion_start': '2 кв. 2024',
                'completion_end': '4 кв. 2025',
                'has_completed': False,
                'developer': 'Антон Хаус',
                'studio_price': 2.8,
                'one_room_price': 2.8,
                'two_room_price': 3.5,
                'three_room_price': 4.2,
                'four_room_price': 5.8,
                'is_featured': False
            },
            {
                'name': 'Университетский 2',
                'price_from': 3.5,
                'city': 'Уфа',
                'district': 'Октябрьский',
                'street': 'Академическая',
                'commute_time': '9 мин.',
                'house_type': 'apartment',
                'area_from': 55.0,
                'area_to': 100.0,
                'status': 'completed',
                'house_class': 'comfort',
                'finishing': 'finished',
                'rooms': '2',
                'total_apartments': 267,
                'completion_start': '3 кв. 2023',
                'completion_end': '1 кв. 2025',
                'has_completed': True,
                'developer': 'Антон Хаус',
                'studio_price': 3.5,
                'one_room_price': 3.8,
                'two_room_price': 3.5,
                'three_room_price': 4.8,
                'four_room_price': 6.2,
                'is_featured': False
            },
            {
                'name': 'Бизнес Центр',
                'price_from': 7.2,
                'city': 'Уфа',
                'district': 'Ленинский',
                'street': 'Деловой центр',
                'commute_time': '3 мин.',
                'house_type': 'penthouse',
                'area_from': 250.0,
                'area_to': 500.0,
                'status': 'completed',
                'house_class': 'premium',
                'finishing': 'finished',
                'rooms': '4',
                'total_apartments': 34,
                'completion_start': '1 кв. 2023',
                'completion_end': '3 кв. 2024',
                'has_completed': True,
                'developer': 'Антон Хаус',
                'studio_price': 7.2,
                'one_room_price': 8.5,
                'two_room_price': 11.2,
                'three_room_price': 15.8,
                'four_room_price': 24.5,
                'is_featured': False
            },
            {
                'name': 'Парк Горького',
                'price_from': 4.9,
                'city': 'Уфа',
                'district': 'Калининский',
                'street': 'Парк Горького',
                'commute_time': '11 мин.',
                'house_type': 'apartment',
                'area_from': 60.0,
                'area_to': 120.0,
                'status': 'construction',
                'house_class': 'comfort',
                'finishing': 'unfinished',
                'rooms': '2',
                'total_apartments': 223,
                'completion_start': '4 кв. 2024',
                'completion_end': '3 кв. 2025',
                'has_completed': False,
                'developer': 'Антон Хаус',
                'studio_price': 4.9,
                'one_room_price': 5.2,
                'two_room_price': 4.9,
                'three_room_price': 6.8,
                'four_room_price': 9.2,
                'is_featured': False
            },
            {
                'name': 'Спортивная 2',
                'price_from': 3.7,
                'city': 'Уфа',
                'district': 'Орджоникидзевский',
                'street': 'Спортивная',
                'commute_time': '13 мин.',
                'house_type': 'apartment',
                'area_from': 48.0,
                'area_to': 92.0,
                'status': 'completed',
                'house_class': 'economy',
                'finishing': 'finished',
                'rooms': '2',
                'total_apartments': 189,
                'completion_start': '2 кв. 2024',
                'completion_end': '4 кв. 2024',
                'has_completed': True,
                'developer': 'Антон Хаус',
                'studio_price': 3.7,
                'one_room_price': 3.9,
                'two_room_price': 3.7,
                'three_room_price': 4.9,
                'four_room_price': 6.5,
                'is_featured': False
            },
            {
                'name': 'Молодежная 2',
                'price_from': 3.3,
                'city': 'Уфа',
                'district': 'Советский',
                'street': 'Молодежная',
                'commute_time': '17 мин.',
                'house_type': 'apartment',
                'area_from': 42.0,
                'area_to': 82.0,
                'status': 'construction',
                'house_class': 'economy',
                'finishing': 'unfinished',
                'rooms': '1',
                'total_apartments': 334,
                'completion_start': '1 кв. 2024',
                'completion_end': '2 кв. 2025',
                'has_completed': False,
                'developer': 'Антон Хаус',
                'studio_price': 3.3,
                'one_room_price': 3.3,
                'two_room_price': 4.1,
                'three_room_price': 4.9,
                'four_room_price': 6.5,
                'is_featured': False
            }
        ]
        
        # Создаем объекты ЖК
        for data in complexes_data:
            ResidentialComplex.objects.create(**data)
        
        self.stdout.write(
            self.style.SUCCESS(f'Успешно создано {len(complexes_data)} жилых комплексов')
        ) 